# Generated by Django 5.0.1 on 2024-06-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_engine', '0002_movie_cast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='cast',
            new_name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.TextField(default=''),
        ),
    ]
