# Generated by Django 5.0.1 on 2024-06-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_engine', '0005_rename_songsgenre_songslanguage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='genre',
            new_name='language',
        ),
    ]
