# Generated by Django 5.0.1 on 2024-06-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_engine', '0006_rename_genre_songs_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
